package de.fhdw.webshop.customer;

import de.fhdw.webshop.order.Order;
import de.fhdw.webshop.order.OrderItem;
import de.fhdw.webshop.order.OrderRepository;
import de.fhdw.webshop.product.Product;
import de.fhdw.webshop.product.ProductRepository;
import de.fhdw.webshop.product.dto.PriceSoldEntry;
import de.fhdw.webshop.product.dto.ProductStatisticsResponse;
import jakarta.persistence.EntityNotFoundException;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class StatisticsService {

    private final OrderRepository orderRepository;
    private final ProductRepository productRepository;

    /** US #29 — Revenue generated by a customer between two dates. */
    public RevenueStatisticsResponse getCustomerRevenue(Long customerId, LocalDate from, LocalDate to) {
        Instant fromInstant = from.atStartOfDay().toInstant(ZoneOffset.UTC);
        Instant toInstant = to.plusDays(1).atStartOfDay().toInstant(ZoneOffset.UTC);

        List<Order> orders = orderRepository.findByCustomerIdAndCreatedAtBetween(customerId, fromInstant, toInstant);
        BigDecimal totalRevenue = orders.stream()
                .map(Order::getTotalPrice)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        return new RevenueStatisticsResponse(customerId, from, to, orders.size(), totalRevenue);
    }

    /** US #34, #89 — Units sold, revenue, and price breakdown for a specific product between two dates. */
    public ProductStatisticsResponse getProductStatistics(Long productId, LocalDate from, LocalDate to) {
        Instant fromInstant = from.atStartOfDay().toInstant(ZoneOffset.UTC);
        Instant toInstant = to.plusDays(1).atStartOfDay().toInstant(ZoneOffset.UTC);

        Product product = productRepository.findById(productId)
                .orElseThrow(() -> new EntityNotFoundException("Product not found: " + productId));
        BigDecimal rrp = product.getRecommendedRetailPrice();

        List<OrderItem> orderItems = orderRepository.findOrderItemsByProductIdAndDateRange(productId, fromInstant, toInstant);
        long unitsSold = orderItems.stream().mapToLong(OrderItem::getQuantity).sum();
        BigDecimal totalRevenue = orderItems.stream()
                .map(oi -> oi.getPriceAtOrderTime().multiply(BigDecimal.valueOf(oi.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        // Group by price (sorted descending) to show at which prices the product was sold
        Map<BigDecimal, Long> priceToUnits = new LinkedHashMap<>();
        for (OrderItem oi : orderItems) {
            priceToUnits.merge(oi.getPriceAtOrderTime(), (long) oi.getQuantity(), Long::sum);
        }
        List<PriceSoldEntry> priceBreakdown = priceToUnits.entrySet().stream()
                .sorted(Map.Entry.<BigDecimal, Long>comparingByKey().reversed())
                .map(e -> new PriceSoldEntry(e.getKey(), e.getValue()))
                .toList();

        // Standard price: sold at or above current RRP; discounted: sold below RRP
        long standardPriceSalesCount = orderItems.stream()
                .filter(oi -> oi.getPriceAtOrderTime().compareTo(rrp) >= 0)
                .mapToLong(OrderItem::getQuantity)
                .sum();
        long discountedSalesCount = unitsSold - standardPriceSalesCount;

        return new ProductStatisticsResponse(
                productId, from, to,
                unitsSold, totalRevenue,
                standardPriceSalesCount, discountedSalesCount,
                priceBreakdown);
    }
}
