package de.fhdw.webshop.customer;

import de.fhdw.webshop.order.Order;
import de.fhdw.webshop.order.OrderItem;
import de.fhdw.webshop.order.OrderRepository;
import de.fhdw.webshop.product.dto.ProductStatisticsResponse;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.List;

@Service
@RequiredArgsConstructor
public class StatisticsService {

    private final OrderRepository orderRepository;

    /** US #29 — Revenue generated by a customer between two dates. */
    public RevenueStatisticsResponse getCustomerRevenue(Long customerId, LocalDate from, LocalDate to) {
        Instant fromInstant = from.atStartOfDay().toInstant(ZoneOffset.UTC);
        Instant toInstant = to.plusDays(1).atStartOfDay().toInstant(ZoneOffset.UTC);

        List<Order> orders = orderRepository.findByCustomerIdAndCreatedAtBetween(customerId, fromInstant, toInstant);
        BigDecimal totalRevenue = orders.stream()
                .map(Order::getTotalPrice)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        return new RevenueStatisticsResponse(customerId, from, to, orders.size(), totalRevenue);
    }

    /** US #34 — Units sold and revenue for a specific product between two dates. */
    public ProductStatisticsResponse getProductStatistics(Long productId, LocalDate from, LocalDate to) {
        Instant fromInstant = from.atStartOfDay().toInstant(ZoneOffset.UTC);
        Instant toInstant = to.plusDays(1).atStartOfDay().toInstant(ZoneOffset.UTC);

        List<OrderItem> orderItems = orderRepository.findOrderItemsByProductIdAndDateRange(productId, fromInstant, toInstant);
        long unitsSold = orderItems.stream().mapToLong(OrderItem::getQuantity).sum();
        BigDecimal totalRevenue = orderItems.stream()
                .map(orderItem -> orderItem.getPriceAtOrderTime()
                        .multiply(BigDecimal.valueOf(orderItem.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        return new ProductStatisticsResponse(productId, from, to, unitsSold, totalRevenue);
    }
}
