CREATE TABLE product_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT,
    user_id BIGINT,
    rating INTEGER,
    comment VARCHAR(1000),
    created_at TIMESTAMP,
    source VARCHAR(255)
);